### ISSUE TITLE
Middleware for MassTransit

### ISSUE THREAD

**Issue by ape-box** [honeycombio/libhoney-dotnet#9]
Hi @martinjt,
inspired by your talk on NDC Oslo, I decided to do a spike for MassTransit, see https://github.com/ape-box/honeycomb/tree/masstransit

I think it would be nice to publish it as nuget package.
I was wondering if you would be interested in merging the version for MassTransit, or would prefer to keep it separate.

**Comment by martinjt** [comment]
First of all, thanks for listening to my rant, hope it was useful!

Second, sorry for the delay in response, I saw it, and needed to digest what I thought was the right approach.

Third, you're awesome dude.  I'm so glad that someone found something useful with the library!

I'm honestly not sure which is the best way to go with the add-ons.  There's no reason you couldn't publish this separately with a dependency on the core Honeycomb library instead of the AspNetCore one.

As MassTransit is more specific, I'm not sure it sits in the repo that well, as I can't maintain that.

That said, keeping things in consistent versions is good, so I'm totally torn.

I'd say that the first thing to do would be to think about separating Honeycomb.MassTransit into it's own repo.  Then changing the csproj to point to the Honeycomb package, not the project.  Incidentally, it's what I need to do with the AspNetCore project too.

**Comment by ape-box** [comment]
Thank you for doing it ;)

I like when libraries are kept in a single official org, so it's up to you if you want to keep the Honeycomb library as a personal (separate) repo, or to create a dedicated organization (I'm reading more than said 😅 ).

In either case, I'm happy to maintain the MassTransit add-on, wherever it is located 👍 .

On a side note, I just started a new job, and won't be able to run it in production until next year, probably; but I'm happy to work on it in the meantime.

On another side note, if you want I can spare one hour here and there ...

**Comment by martinjt** [comment]
Added you to a channel in the pollinators slack so we can discuss 👍

**Comment by MikeGoldsmith** [comment]
We’re going to close this for now as we're moving more towards supporting OpenTelemetry SDKs. Feel free to re-open if it’s still relevant.
